//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Spe_Hardware.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_Spe_Hardware_Spe_Hardware_FlashDriver::NativeRead___STATIC__I4__I4__U4__SZARRAY_U1,
    NULL,
    Library_Spe_Hardware_Spe_Hardware_FlashDriver::NativeWrite___STATIC__I4__I4__U4__SZARRAY_U1,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Spe_Hardware =
{
    "Spe.Hardware", 
    0x7AEDB87F,
    method_lookup
};

