//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SPE_HARDWARE_H_
#define _SPE_HARDWARE_H_

#include <TinyCLR_Interop.h>
struct Library_Spe_Hardware_Spe_Hardware_FlashDriver
{
    TINYCLR_NATIVE_DECLARE(NativeRead___STATIC__I4__I4__U4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(NativeWrite___STATIC__I4__I4__U4__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Spe_Hardware;

#endif  //_SPE_HARDWARE_H_
